DROP TRIGGER IF EXISTS update_contractual_obligations_updated_at ON contractual_obligations;
DROP TRIGGER IF EXISTS update_committee_decisions_updated_at ON committee_decisions;
DROP TRIGGER IF EXISTS update_committees_updated_at ON committees;
DROP TRIGGER IF EXISTS update_corrective_actions_updated_at ON corrective_actions;
DROP TRIGGER IF EXISTS update_audit_findings_updated_at ON audit_findings;
DROP TRIGGER IF EXISTS update_audits_updated_at ON audits;
DROP TABLE IF EXISTS evidence;
DROP TABLE IF EXISTS contractual_obligations;
DROP TABLE IF EXISTS committee_decisions;
DROP TABLE IF EXISTS committees;
DROP TABLE IF EXISTS corrective_actions;
DROP TABLE IF EXISTS audit_findings;
DROP TABLE IF EXISTS audits;
DROP TYPE IF EXISTS decision_outcome;
DROP TYPE IF EXISTS committee_status;
DROP TYPE IF EXISTS committee_type;
DROP TYPE IF EXISTS capa_status;
DROP TYPE IF EXISTS finding_status;
DROP TYPE IF EXISTS finding_severity;
DROP TYPE IF EXISTS audit_status;
DROP TYPE IF EXISTS audit_type;
DROP TYPE IF EXISTS evidence_model;
