DROP TRIGGER IF EXISTS update_nexus_config_updated_at ON nexus_config;
DROP TRIGGER IF EXISTS update_nexus_waivers_updated_at ON nexus_waivers;
DROP TRIGGER IF EXISTS update_nexus_vulnerabilities_updated_at ON nexus_vulnerabilities;
DROP TRIGGER IF EXISTS update_nexus_scan_reports_updated_at ON nexus_scan_reports;
DROP TRIGGER IF EXISTS update_nexus_applications_updated_at ON nexus_applications;
DROP TRIGGER IF EXISTS update_nexus_products_updated_at ON nexus_products;
DROP TABLE IF EXISTS nexus_config;
DROP TABLE IF EXISTS nexus_sync_logs;
DROP TABLE IF EXISTS nexus_alerts;
DROP TABLE IF EXISTS nexus_kpi_snapshots;
DROP TABLE IF EXISTS nexus_waivers;
DROP TABLE IF EXISTS nexus_policy_violations;
DROP TABLE IF EXISTS nexus_vulnerabilities;
DROP TABLE IF EXISTS nexus_components;
DROP TABLE IF EXISTS nexus_scan_reports;
DROP TABLE IF EXISTS product_application_mapping;
DROP TABLE IF EXISTS nexus_applications;
DROP TABLE IF EXISTS nexus_organizations;
DROP TABLE IF EXISTS nexus_products;
DROP TYPE IF EXISTS sync_status;
DROP TYPE IF EXISTS alert_type;
DROP TYPE IF EXISTS license_risk;
DROP TYPE IF EXISTS threat_level_type;
DROP TYPE IF EXISTS nexus_waiver_status;
DROP TYPE IF EXISTS nexus_vuln_status;
DROP TYPE IF EXISTS exploitability;
DROP TYPE IF EXISTS reachability;
DROP TYPE IF EXISTS dependency_type;
DROP TYPE IF EXISTS scan_stage;
DROP TYPE IF EXISTS business_criticality;
DROP TYPE IF EXISTS product_grade;
