-- Down: 030_nexus_report_enhancements
DROP TRIGGER IF EXISTS update_nexus_component_impact_updated_at ON nexus_component_impact;
DROP TRIGGER IF EXISTS update_nexus_evolution_snapshots_updated_at ON nexus_evolution_snapshots;
DROP TABLE IF EXISTS nexus_component_impact;
DROP TABLE IF EXISTS nexus_evolution_snapshots;
ALTER TABLE nexus_components DROP COLUMN IF EXISTS component_hash;
ALTER TABLE nexus_components DROP COLUMN IF EXISTS format;
ALTER TABLE nexus_components DROP COLUMN IF EXISTS coordinates;
ALTER TABLE nexus_components DROP COLUMN IF EXISTS display_name;
ALTER TABLE nexus_components DROP COLUMN IF EXISTS proprietary;
ALTER TABLE nexus_components DROP COLUMN IF EXISTS match_state;
ALTER TABLE nexus_policy_violations DROP COLUMN IF EXISTS report_id;
ALTER TABLE nexus_policy_violations DROP COLUMN IF EXISTS policy_id;
ALTER TABLE nexus_policy_violations DROP COLUMN IF EXISTS constraint_id;
ALTER TABLE nexus_policy_violations DROP COLUMN IF EXISTS component_hash;
ALTER TABLE nexus_policy_violations DROP COLUMN IF EXISTS component_format;
ALTER TABLE nexus_policy_violations DROP COLUMN IF EXISTS component_coordinates;
ALTER TABLE nexus_policy_violations DROP COLUMN IF EXISTS display_name;
ALTER TABLE nexus_policy_violations DROP COLUMN IF EXISTS proprietary;
ALTER TABLE nexus_policy_violations DROP COLUMN IF EXISTS match_state;
ALTER TABLE nexus_policy_violations DROP COLUMN IF EXISTS security_issue_ref_id;
ALTER TABLE nexus_policy_violations DROP COLUMN IF EXISTS security_issue_severity;
ALTER TABLE nexus_policy_violations DROP COLUMN IF EXISTS cve_id;
ALTER TABLE nexus_policy_violations DROP COLUMN IF EXISTS threat_category;
ALTER TABLE nexus_policy_violations DROP COLUMN IF EXISTS open_time;
ALTER TABLE nexus_policy_violations DROP COLUMN IF EXISTS waive_time;
ALTER TABLE nexus_policy_violations DROP COLUMN IF EXISTS fix_time;
ALTER TABLE nexus_policy_violations DROP COLUMN IF EXISTS is_waived;
ALTER TABLE nexus_policy_violations DROP COLUMN IF EXISTS is_legacy;
ALTER TABLE nexus_scan_reports DROP COLUMN IF EXISTS report_title;
ALTER TABLE nexus_scan_reports DROP COLUMN IF EXISTS commit_hash;
ALTER TABLE nexus_scan_reports DROP COLUMN IF EXISTS initiator;
ALTER TABLE nexus_scan_reports DROP COLUMN IF EXISTS embeddable_report_html_url;
ALTER TABLE nexus_scan_reports DROP COLUMN IF EXISTS report_pdf_url;
ALTER TABLE nexus_scan_reports DROP COLUMN IF EXISTS report_data_url;
ALTER TABLE nexus_scan_reports DROP COLUMN IF EXISTS total_violations;
ALTER TABLE nexus_scan_reports DROP COLUMN IF EXISTS policy_evaluation_status;
ALTER TABLE nexus_scan_reports DROP COLUMN IF EXISTS application_uuid;
ALTER TABLE nexus_scan_reports DROP COLUMN IF EXISTS component_hashes;
