/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { VEGRequest } from "./types";

export interface RealVEGRequest extends VEGRequest {
  region?: string;
  businessLine?: string;
  products?: string;
  dealTypeStr?: string;
  tcvK?: number;
  ipMaintenanceK?: number;
  saasK?: number;
  psVegK?: number;
  wlVegInvestmentMD?: number;
  rawDecision?: string;
  salesStatusStr?: string;
  comment?: string;
}

export const REAL_VEG_REQUESTS: RealVEGRequest[] = [
  {
    "id": "21-2023-001",
    "title": "COLLINE_MIZUHO AMERICAS SERVICES LLC_N_1123",
    "type": "RFP",
    "status": "SUBMITTED",
    "client": "Mizuho",
    "marginEstimate": 81,
    "workloadMD": 175,
    "financeState": "APPROVED",
    "salesState": "APPROVED",
    "productState": "APPROVED",
    "legalState": "APPROVED",
    "owner": "Terrance Baum",
    "date": "2023-05-16",
    "region": "Americas",
    "businessLine": "Colline",
    "products": "Colline",
    "dealTypeStr": "Go n Go",
    "tcvK": 1600,
    "ipMaintenanceK": 0,
    "saasK": 0,
    "psVegK": 300,
    "wlVegInvestmentMD": 0,
    "rawDecision": "GO FINAL",
    "salesStatusStr": "0",
    "comment": "2023"
  },
  {
    "id": "21-2023-002",
    "title": "DIGITAL APPS_MIF_N_1223 + SOLIAM_MIF_N_1223",
    "type": "RFP",
    "status": "SUBMITTED",
    "client": "MIF",
    "marginEstimate": 100,
    "workloadMD": 350,
    "financeState": "APPROVED",
    "salesState": "APPROVED",
    "productState": "APPROVED",
    "legalState": "APPROVED",
    "owner": "Dan Cohen",
    "date": "2023-05-16",
    "region": "EU",
    "businessLine": "Soliam",
    "products": "Soliam - Custodix",
    "dealTypeStr": "Go n Go",
    "tcvK": 1509,
    "ipMaintenanceK": 0,
    "saasK": 0,
    "psVegK": 0,
    "wlVegInvestmentMD": 0,
    "rawDecision": "GO FINAL",
    "salesStatusStr": "0",
    "comment": "2023"
  },
  {
    "id": "21-2023-003",
    "title": "Portfolio Take-over",
    "type": "BID_COMMITTEE_OVERSIGHT",
    "status": "SUBMITTED",
    "client": "ERGO",
    "marginEstimate": 75,
    "workloadMD": 350,
    "financeState": "APPROVED",
    "salesState": "APPROVED",
    "productState": "APPROVED",
    "legalState": "APPROVED",
    "owner": "Guillaume De Vauxclairs",
    "date": "2023-05-16",
    "region": "EU",
    "businessLine": "Solife",
    "products": "Solife - Digital",
    "dealTypeStr": "Bid n Bid",
    "tcvK": 0,
    "ipMaintenanceK": 0,
    "saasK": 0,
    "psVegK": 0,
    "wlVegInvestmentMD": 0,
    "rawDecision": "BID",
    "salesStatusStr": "BID",
    "comment": "BID"
  },
  {
    "id": "21-2023-004",
    "title": "Partnership",
    "type": "BID_COMMITTEE_OVERSIGHT",
    "status": "SUBMITTED",
    "client": "Grant Thornton Partnership",
    "marginEstimate": 75,
    "workloadMD": 350,
    "financeState": "APPROVED",
    "salesState": "APPROVED",
    "productState": "APPROVED",
    "legalState": "APPROVED",
    "owner": "Alan Blanchard",
    "date": "2023-05-16",
    "region": "UK",
    "businessLine": "Regulatory",
    "products": "Agile Reporter",
    "dealTypeStr": "Bid n Bid",
    "tcvK": 0,
    "ipMaintenanceK": 0,
    "saasK": 0,
    "psVegK": 0,
    "wlVegInvestmentMD": 0,
    "rawDecision": "BID",
    "salesStatusStr": "BID",
    "comment": "BID"
  },
  {
    "id": "21-2023-005",
    "title": "REGULATORY_BNP PARIBAS_N_1223",
    "type": "RFP",
    "status": "SUBMITTED",
    "client": "BNP Paribas",
    "marginEstimate": 100,
    "workloadMD": 350,
    "financeState": "APPROVED",
    "salesState": "APPROVED",
    "productState": "APPROVED",
    "legalState": "APPROVED",
    "owner": "Thomas Filipovits",
    "date": "2023-05-18",
    "region": "Americas",
    "businessLine": "Regulatory",
    "products": "Agile reporter",
    "dealTypeStr": "Go n Go",
    "tcvK": 3220,
    "ipMaintenanceK": 0,
    "saasK": 0,
    "psVegK": 0,
    "wlVegInvestmentMD": 0,
    "rawDecision": "GO FINAL",
    "salesStatusStr": "0",
    "comment": "2023"
  },
  {
    "id": "22-2023-006",
    "title": "Veggo Employee Benefits",
    "type": "BID_COMMITTEE_OVERSIGHT",
    "status": "SUBMITTED",
    "client": "FOYER Assurance",
    "marginEstimate": 75,
    "workloadMD": 350,
    "financeState": "APPROVED",
    "salesState": "APPROVED",
    "productState": "APPROVED",
    "legalState": "APPROVED",
    "owner": "Anne Thiel",
    "date": "2023-05-23",
    "region": "EU",
    "businessLine": "Digital",
    "products": "DigApp : DigJourney Group Souscription, BIA, : DigJourney Affiliiates & Corportates (Zurich UK)",
    "dealTypeStr": "Bid n Bid",
    "tcvK": 0,
    "ipMaintenanceK": 0,
    "saasK": 0,
    "psVegK": 0,
    "wlVegInvestmentMD": 0,
    "rawDecision": "BID",
    "salesStatusStr": "BID",
    "comment": "BID"
  },
  {
    "id": "22-2023-007",
    "title": "COLLINE_CITIBANK, N.A. (LONDON)_N_0823",
    "type": "RFP",
    "status": "SUBMITTED",
    "client": "CITI Bank",
    "marginEstimate": 100,
    "workloadMD": 350,
    "financeState": "APPROVED",
    "salesState": "APPROVED",
    "productState": "APPROVED",
    "legalState": "APPROVED",
    "owner": "Tom Landi",
    "date": "2023-05-23",
    "region": "UK",
    "businessLine": "Colline",
    "products": "Colline",
    "dealTypeStr": "Go n Go",
    "tcvK": 1800,
    "ipMaintenanceK": 0,
    "saasK": 0,
    "psVegK": 0,
    "wlVegInvestmentMD": 0,
    "rawDecision": "GO FINAL",
    "salesStatusStr": "0",
    "comment": "2023"
  },
  {
    "id": "22-2023-008",
    "title": "Portfolio Take-over",
    "type": "RFP",
    "status": "REJECTED",
    "client": "ERGO",
    "marginEstimate": 59,
    "workloadMD": 4787,
    "financeState": "APPROVED",
    "salesState": "APPROVED",
    "productState": "APPROVED",
    "legalState": "APPROVED",
    "owner": "Guillaume De Vauxclairs",
    "date": "2023-05-23",
    "region": "EU",
    "businessLine": "Solife",
    "products": "Solife - Digital",
    "dealTypeStr": "Go n Go",
    "tcvK": 10369,
    "ipMaintenanceK": 0,
    "saasK": 0,
    "psVegK": 4201,
    "wlVegInvestmentMD": 963,
    "rawDecision": "No GO",
    "salesStatusStr": "0",
    "comment": "2023"
  },
  {
    "id": "22-2023-009",
    "title": "REGULATORY_TORONTO-DOMINION BANK (THE)_N_0324\\n",
    "type": "RFP",
    "status": "SUBMITTED",
    "client": "Toronto Dominion",
    "marginEstimate": 100,
    "workloadMD": 350,
    "financeState": "APPROVED",
    "salesState": "APPROVED",
    "productState": "APPROVED",
    "legalState": "APPROVED",
    "owner": "Terrance Baum",
    "date": "2023-05-23",
    "region": "Americas",
    "businessLine": "Regulatory",
    "products": "Agile reporter",
    "dealTypeStr": "Go n Go",
    "tcvK": 6050,
    "ipMaintenanceK": 0,
    "saasK": 0,
    "psVegK": 0,
    "wlVegInvestmentMD": 0,
    "rawDecision": "GO FINAL",
    "salesStatusStr": "0",
    "comment": "2023"
  },
  {
    "id": "22-2023-010",
    "title": "SOLIAM_ARGENTA SPAARBANK NV (ANTWERP)_U_0623",
    "type": "RFP",
    "status": "SUBMITTED",
    "client": "Argenta BE",
    "marginEstimate": 87,
    "workloadMD": 10.5,
    "financeState": "APPROVED",
    "salesState": "APPROVED",
    "productState": "APPROVED",
    "legalState": "APPROVED",
    "owner": "Dan Cohen",
    "date": "2023-05-24",
    "region": "EU",
    "businessLine": "Soliam",
    "products": "Soliam",
    "dealTypeStr": "Go n Go",
    "tcvK": 92,
    "ipMaintenanceK": 0,
    "saasK": 0,
    "psVegK": 12,
    "wlVegInvestmentMD": 161,
    "rawDecision": "GO without Committee FINAL",
    "salesStatusStr": "0",
    "comment": "2023"
  },
  {
    "id": "22-2023-011",
    "title": "SOLIAM_AG INSURANCE_U_0623",
    "type": "RFP",
    "status": "SUBMITTED",
    "client": "AG Insurance",
    "marginEstimate": 75,
    "workloadMD": 171,
    "financeState": "APPROVED",
    "salesState": "APPROVED",
    "productState": "APPROVED",
    "legalState": "APPROVED",
    "owner": "Dan Cohen",
    "date": "2023-05-24",
    "region": "EU",
    "businessLine": "Soliam",
    "products": "Soliam",
    "dealTypeStr": "Go n Go",
    "tcvK": 89,
    "ipMaintenanceK": 0,
    "saasK": 0,
    "psVegK": 89,
    "wlVegInvestmentMD": 0,
    "rawDecision": "GO without Committee FINAL",
    "salesStatusStr": "0",
    "comment": "2023"
  },
  {
    "id": "23-2023-012",
    "title": "SOLIFE_ERGO_N_0324 + DIGITAL APPS_ERGO_N_0624",
    "type": "RFP",
    "status": "SUBMITTED",
    "client": "ERGO",
    "marginEstimate": 100,
    "workloadMD": 350,
    "financeState": "APPROVED",
    "salesState": "APPROVED",
    "productState": "APPROVED",
    "legalState": "APPROVED",
    "owner": "Guillaume De Vauxclairs",
    "date": "2023-05-30",
    "region": "EU",
    "businessLine": "Solife",
    "products": "Solife - Digital",
    "dealTypeStr": "Go n Go",
    "tcvK": 6800,
    "ipMaintenanceK": 0,
    "saasK": 0,
    "psVegK": 0,
    "wlVegInvestmentMD": 0,
    "rawDecision": "GO FINAL",
    "salesStatusStr": "0",
    "comment": "2023"
  },
  {
    "id": "23-2023-013",
    "title": "Megara for Digital Assets",
    "type": "BID_COMMITTEE_OVERSIGHT",
    "status": "SUBMITTED",
    "client": "Caceis France",
    "marginEstimate": 75,
    "workloadMD": 350,
    "financeState": "APPROVED",
    "salesState": "APPROVED",
    "productState": "APPROVED",
    "legalState": "APPROVED",
    "owner": "Ilyes Mainsi",
    "date": "2023-05-29",
    "region": "EU",
    "businessLine": "Megara",
    "products": "Megara",
    "dealTypeStr": "Bid n Bid",
    "tcvK": 0,
    "ipMaintenanceK": 0,
    "saasK": 0,
    "psVegK": 0,
    "wlVegInvestmentMD": 0,
    "rawDecision": "BID",
    "salesStatusStr": "BID",
    "comment": "BID"
  },
  {
    "id": "23-2023-014",
    "title": "REGULATORY_LLOYDS BANK PLC (LONDON)_N_1023",
    "type": "RFP",
    "status": "SUBMITTED",
    "client": "Lloyds Bank",
    "marginEstimate": 98,
    "workloadMD": 40,
    "financeState": "APPROVED",
    "salesState": "APPROVED",
    "productState": "APPROVED",
    "legalState": "APPROVED",
    "owner": "Samuel Welford",
    "date": "2023-05-30",
    "region": "UK",
    "businessLine": "Regulatory",
    "products": "Agile reporter",
    "dealTypeStr": "Go n Go",
    "tcvK": 2903,
    "ipMaintenanceK": 0,
    "saasK": 0,
    "psVegK": 69,
    "wlVegInvestmentMD": 456,
    "rawDecision": "GO FINAL",
    "salesStatusStr": "0",
    "comment": "2023"
  },
  {
    "id": "23-2023-015",
    "title": "DIGITAL APPS_GENERALI _N_1223\\nGENERALI - XCHANGER FLUX TITRES + CUSTODIX\\n",
    "type": "RFP",
    "status": "SUBMITTED",
    "client": "GENERALI",
    "marginEstimate": 93,
    "workloadMD": 40,
    "financeState": "APPROVED",
    "salesState": "APPROVED",
    "productState": "APPROVED",
    "legalState": "APPROVED",
    "owner": "Mathieu Reynier",
    "date": "2023-05-30",
    "region": "EU",
    "businessLine": "Digital",
    "products": "Custodix XChanger",
    "dealTypeStr": "Go n Go",
    "tcvK": 982,
    "ipMaintenanceK": 0,
    "saasK": 0,
    "psVegK": 69,
    "wlVegInvestmentMD": 456,
    "rawDecision": "GO FINAL",
    "salesStatusStr": "0",
    "comment": "2023"
  },
  {
    "id": "23-2023-016",
    "title": "ECMS + Reshaping of current core applications (lLuxembourg)",
    "type": "BID_COMMITTEE_OVERSIGHT",
    "status": "SUBMITTED",
    "client": "Intesa SanPaolo Luxembourg",
    "marginEstimate": 75,
    "workloadMD": 350,
    "financeState": "APPROVED",
    "salesState": "APPROVED",
    "productState": "APPROVED",
    "legalState": "APPROVED",
    "owner": "Raphael Suria",
    "date": "2023-05-30",
    "region": "EU",
    "businessLine": "Megara",
    "products": "Megara - Easy Collateral - Colline",
    "dealTypeStr": "Bid n Bid",
    "tcvK": 0,
    "ipMaintenanceK": 0,
    "saasK": 0,
    "psVegK": 0,
    "wlVegInvestmentMD": 0,
    "rawDecision": "BID",
    "salesStatusStr": "BID",
    "comment": "BID"
  },
  {
    "id": "23-2023-017",
    "title": "Service RUN\\nSOLIAM_SOGELIFE_U_1223\\n",
    "type": "RFP",
    "status": "SUBMITTED",
    "client": "Sogelife",
    "marginEstimate": 75,
    "workloadMD": 350,
    "financeState": "APPROVED",
    "salesState": "APPROVED",
    "productState": "APPROVED",
    "legalState": "APPROVED",
    "owner": "Anne Thiel",
    "date": "2023-05-30",
    "region": "EU",
    "businessLine": "Soliam",
    "products": "Soliam",
    "dealTypeStr": "Go n Go",
    "tcvK": 454,
    "ipMaintenanceK": 0,
    "saasK": 0,
    "psVegK": 454,
    "wlVegInvestmentMD": 0,
    "rawDecision": "GO FINAL",
    "salesStatusStr": "0",
    "comment": "2023"
  },
  {
    "id": "24-2023-018",
    "title": "MEGARA_MILLENNIUM BCP_C_0324",
    "type": "BID_COMMITTEE_OVERSIGHT",
    "status": "SUBMITTED",
    "client": "Millenium BCP",
    "marginEstimate": 75,
    "workloadMD": 350,
    "financeState": "APPROVED",
    "salesState": "APPROVED",
    "productState": "APPROVED",
    "legalState": "APPROVED",
    "owner": "Pablo Garmon",
    "date": "2023-06-06",
    "region": "EU",
    "businessLine": "Megara",
    "products": "Megara",
    "dealTypeStr": "Bid n Bid",
    "tcvK": 0,
    "ipMaintenanceK": 0,
    "saasK": 0,
    "psVegK": 0,
    "wlVegInvestmentMD": 0,
    "rawDecision": "BID",
    "salesStatusStr": "BID",
    "comment": "BID"
  },
  {
    "id": "24-2023-019",
    "title": "Clear Bank Agile Reporter",
    "type": "RFP",
    "status": "SUBMITTED",
    "client": "Clear Bank",
    "marginEstimate": 100,
    "workloadMD": 350,
    "financeState": "APPROVED",
    "salesState": "APPROVED",
    "productState": "APPROVED",
    "legalState": "APPROVED",
    "owner": "Tom Landi",
    "date": "2023-06-06",
    "region": "UK",
    "businessLine": "Regulatory",
    "products": "Agile reporter",
    "dealTypeStr": "Go n Go",
    "tcvK": 1181,
    "ipMaintenanceK": 0,
    "saasK": 0,
    "psVegK": 0,
    "wlVegInvestmentMD": 0,
    "rawDecision": "GO FINAL",
    "salesStatusStr": "0",
    "comment": "2023"
  },
  {
    "id": "24-2023-020",
    "title": "Fincite Custodix",
    "type": "RFP",
    "status": "SUBMITTED",
    "client": "Fincite",
    "marginEstimate": 100,
    "workloadMD": 350,
    "financeState": "APPROVED",
    "salesState": "APPROVED",
    "productState": "APPROVED",
    "legalState": "APPROVED",
    "owner": "Alan Blanchard",
    "date": "2023-06-06",
    "region": "UK",
    "businessLine": "Digital",
    "products": "Digital Custodix",
    "dealTypeStr": "Go n Go",
    "tcvK": 416,
    "ipMaintenanceK": 0,
    "saasK": 0,
    "psVegK": 0,
    "wlVegInvestmentMD": 0,
    "rawDecision": "GO FINAL",
    "salesStatusStr": "0",
    "comment": "2023"
  },
  {
    "id": "24-2023-021",
    "title": "Life Star",
    "type": "BID_COMMITTEE_OVERSIGHT",
    "status": "SUBMITTED",
    "client": "LifeStar",
    "marginEstimate": 75,
    "workloadMD": 350,
    "financeState": "APPROVED",
    "salesState": "APPROVED",
    "productState": "APPROVED",
    "legalState": "APPROVED",
    "owner": "Guillaume De Vauxclairs",
    "date": "2023-06-06",
    "region": "EU",
    "businessLine": "Solife",
    "products": "Solife - Digital",
    "dealTypeStr": "Bid n Bid",
    "tcvK": 0,
    "ipMaintenanceK": 0,
    "saasK": 0,
    "psVegK": 0,
    "wlVegInvestmentMD": 0,
    "rawDecision": "BID",
    "salesStatusStr": "BID",
    "comment": "BID"
  },
  {
    "id": "24-2023-022",
    "title": "Portfolio Take-over:\\nSOLIFE_ERGO_N_0324\\n+\\nDIGITAL APPS_ERGO_N_0624",
    "type": "RFP",
    "status": "SUBMITTED",
    "client": "ERGO",
    "marginEstimate": 100,
    "workloadMD": 350,
    "financeState": "APPROVED",
    "salesState": "APPROVED",
    "productState": "APPROVED",
    "legalState": "APPROVED",
    "owner": "Guillaume De Vauxclairs",
    "date": "2023-06-06",
    "region": "EU",
    "businessLine": "Solife",
    "products": "Solife - Digital",
    "dealTypeStr": "Go n Go",
    "tcvK": 6800,
    "ipMaintenanceK": 0,
    "saasK": 0,
    "psVegK": 0,
    "wlVegInvestmentMD": 0,
    "rawDecision": "GO FINAL",
    "salesStatusStr": "0",
    "comment": "2023"
  },
  {
    "id": "24-2023-023",
    "title": "Cloud Migration;\\nCOLLINE_SCOTIABANK (COLLINE - TORONTO)_U_0324\\n",
    "type": "RFP",
    "status": "SUBMITTED",
    "client": "Scotia Bank",
    "marginEstimate": 100,
    "workloadMD": 350,
    "financeState": "APPROVED",
    "salesState": "APPROVED",
    "productState": "APPROVED",
    "legalState": "APPROVED",
    "owner": "Terrance Baum",
    "date": "2023-06-06",
    "region": "Americas",
    "businessLine": "Colline",
    "products": "Colline",
    "dealTypeStr": "Go n Go",
    "tcvK": 460,
    "ipMaintenanceK": 0,
    "saasK": 0,
    "psVegK": 0,
    "wlVegInvestmentMD": 0,
    "rawDecision": "GO FINAL",
    "salesStatusStr": "0",
    "comment": "2023"
  },
  {
    "id": "24-2023-024",
    "title": "Megara for Digital Assets",
    "type": "RFP",
    "status": "SUBMITTED",
    "client": "Caceis France",
    "marginEstimate": 100,
    "workloadMD": 350,
    "financeState": "APPROVED",
    "salesState": "APPROVED",
    "productState": "APPROVED",
    "legalState": "APPROVED",
    "owner": "Ilyes Mainsi",
    "date": "2023-06-06",
    "region": "EU",
    "businessLine": "Megara",
    "products": "Megara",
    "dealTypeStr": "Go n Go",
    "tcvK": 1500,
    "ipMaintenanceK": 0,
    "saasK": 0,
    "psVegK": 0,
    "wlVegInvestmentMD": 0,
    "rawDecision": "GO FINAL",
    "salesStatusStr": "0",
    "comment": "2023"
  },
  {
    "id": "32-2023-025",
    "title": "Megara for Digital Assets",
    "type": "RFP",
    "status": "SUBMITTED",
    "client": "Caceis France",
    "marginEstimate": 100,
    "workloadMD": 350,
    "financeState": "APPROVED",
    "salesState": "APPROVED",
    "productState": "APPROVED",
    "legalState": "APPROVED",
    "owner": "Ilyes Mainsi",
    "date": "2023-08-06",
    "region": "EU",
    "businessLine": "Megara",
    "products": "Megara",
    "dealTypeStr": "Go n Go",
    "tcvK": 1650,
    "ipMaintenanceK": 0,
    "saasK": 0,
    "psVegK": 0,
    "wlVegInvestmentMD": 0,
    "rawDecision": "GO without Committee FINAL",
    "salesStatusStr": "0",
    "comment": "2023"
  },
  {
    "id": "27-2023-026",
    "title": "MEGARA_CCB (ASIA)_N_0823",
    "type": "RFP",
    "status": "SUBMITTED",
    "client": "CCBA",
    "marginEstimate": 73,
    "workloadMD": 823,
    "financeState": "APPROVED",
    "salesState": "APPROVED",
    "productState": "APPROVED",
    "legalState": "APPROVED",
    "owner": "Joseph Kubeyka",
    "date": "2023-06-27",
    "region": "APAC",
    "businessLine": "Megara",
    "products": "Megara",
    "dealTypeStr": "Go n Go",
    "tcvK": 1383,
    "ipMaintenanceK": 0,
    "saasK": 0,
    "psVegK": 374,
    "wlVegInvestmentMD": 88,
    "rawDecision": "GO FINAL",
    "salesStatusStr": "0",
    "comment": "2023"
  },
  {
    "id": "25-2023-027",
    "title": "SOLIAM_BPCE VIE _U_0723",
    "type": "RFP",
    "status": "SUBMITTED",
    "client": "BPCE",
    "marginEstimate": 40,
    "workloadMD": 68.8,
    "financeState": "APPROVED",
    "salesState": "APPROVED",
    "productState": "APPROVED",
    "legalState": "APPROVED",
    "owner": "Anne Thiel",
    "date": "2023-06-13",
    "region": "EU",
    "businessLine": "Soliam",
    "products": "Soliam",
    "dealTypeStr": "Go n Go",
    "tcvK": 49,
    "ipMaintenanceK": 0,
    "saasK": 0,
    "psVegK": 51,
    "wlVegInvestmentMD": 0,
    "rawDecision": "GO FINAL",
    "salesStatusStr": "0",
    "comment": "2023"
  },
  {
    "id": "25-2023-028",
    "title": "SOLIFE_LIFESTAR_U_0823",
    "type": "RFP",
    "status": "SUBMITTED",
    "client": "LifeStar",
    "marginEstimate": 73,
    "workloadMD": 524,
    "financeState": "APPROVED",
    "salesState": "APPROVED",
    "productState": "APPROVED",
    "legalState": "APPROVED",
    "owner": "Guillaume De Vauxclairs",
    "date": "2023-06-13",
    "region": "EU",
    "businessLine": "Solife",
    "products": "Solife - Digital",
    "dealTypeStr": "Go n Go",
    "tcvK": 1367,
    "ipMaintenanceK": 0,
    "saasK": 0,
    "psVegK": 367,
    "wlVegInvestmentMD": 0,
    "rawDecision": "GO FINAL",
    "salesStatusStr": "0",
    "comment": "2023"
  },
  {
    "id": "25-2023-029",
    "title": "AG_INSURANCE_SOLIFE_TECHNICAL_UPGRADE_Q2_2023",
    "type": "RFP",
    "status": "SUBMITTED",
    "client": "AG Insurance",
    "marginEstimate": 75,
    "workloadMD": 124,
    "financeState": "APPROVED",
    "salesState": "APPROVED",
    "productState": "APPROVED",
    "legalState": "APPROVED",
    "owner": "Jerome Bastie",
    "date": "2023-06-13",
    "region": "EU",
    "businessLine": "Solife",
    "products": "Solife",
    "dealTypeStr": "Go n Go",
    "tcvK": 119,
    "ipMaintenanceK": 0,
    "saasK": 0,
    "psVegK": 119,
    "wlVegInvestmentMD": 0,
    "rawDecision": "GO FINAL",
    "salesStatusStr": "0",
    "comment": "2023"
  },
  {
    "id": "25-2023-030",
    "title": "COLLINE_BANCO BPM_N_1223",
    "type": "RFP",
    "status": "SUBMITTED",
    "client": "BPM",
    "marginEstimate": 100,
    "workloadMD": 350,
    "financeState": "APPROVED",
    "salesState": "APPROVED",
    "productState": "APPROVED",
    "legalState": "APPROVED",
    "owner": "Raphael Suria",
    "date": "2023-06-13",
    "region": "EU",
    "businessLine": "Colline",
    "products": "Colline",
    "dealTypeStr": "Go n Go",
    "tcvK": 1181,
    "ipMaintenanceK": 0,
    "saasK": 0,
    "psVegK": 0,
    "wlVegInvestmentMD": 0,
    "rawDecision": "GO FINAL",
    "salesStatusStr": "0",
    "comment": "2023"
  },
  {
    "id": "35-2023-031",
    "title": "COLLINE_TCW GROUP INC. (LOS ANGELES)_R_0523",
    "type": "RFP",
    "status": "SUBMITTED",
    "client": "TCW",
    "marginEstimate": 25,
    "workloadMD": 20,
    "financeState": "APPROVED",
    "salesState": "APPROVED",
    "productState": "APPROVED",
    "legalState": "APPROVED",
    "owner": "David Hardy",
    "date": "2023-08-26",
    "region": "Americas",
    "businessLine": "Colline",
    "products": "Colline",
    "dealTypeStr": "Go n Go",
    "tcvK": 55,
    "ipMaintenanceK": 0,
    "saasK": 0,
    "psVegK": 41,
    "wlVegInvestmentMD": 0,
    "rawDecision": "GO FINAL",
    "salesStatusStr": "0",
    "comment": "2023"
  },
  {
    "id": "25-2023-032",
    "title": "DIGITAL APPS_GENERALI _U_0324",
    "type": "RFP",
    "status": "SUBMITTED",
    "client": "TCW",
    "marginEstimate": 84,
    "workloadMD": 90,
    "financeState": "APPROVED",
    "salesState": "APPROVED",
    "productState": "APPROVED",
    "legalState": "APPROVED",
    "owner": "Mathieu Reynier",
    "date": "2023-06-13",
    "region": "EU",
    "businessLine": "Digital",
    "products": "Digital",
    "dealTypeStr": "Go n Go",
    "tcvK": 381,
    "ipMaintenanceK": 0,
    "saasK": 0,
    "psVegK": 60,
    "wlVegInvestmentMD": 100,
    "rawDecision": "GO FINAL",
    "salesStatusStr": "0",
    "comment": "2023"
  },
  {
    "id": "50-2023-033",
    "title": "REGULATORY_SUMITOMO MITSUI TRUST BANK (SINGAPORE)_U_0623",
    "type": "RFP",
    "status": "SUBMITTED",
    "client": "SMTB",
    "marginEstimate": 56,
    "workloadMD": 132,
    "financeState": "APPROVED",
    "salesState": "APPROVED",
    "productState": "APPROVED",
    "legalState": "APPROVED",
    "owner": "Nimoh Mohankumar",
    "date": "2023-12-06",
    "region": "APAC",
    "businessLine": "Regulatory",
    "products": "Agile reporter",
    "dealTypeStr": "Go n Go",
    "tcvK": 420,
    "ipMaintenanceK": 0,
    "saasK": 0,
    "psVegK": 185,
    "wlVegInvestmentMD": 0,
    "rawDecision": "GO without Committee FINAL",
    "salesStatusStr": "0",
    "comment": "2023"
  },
  {
    "id": "50-2023-034",
    "title": "REGULATORY_MITSUBISHI UFJ TRUST & BANKING CORPORATION (SINGAPORE)_U_0623",
    "type": "RFP",
    "status": "SUBMITTED",
    "client": "MUTB",
    "marginEstimate": 57,
    "workloadMD": 75,
    "financeState": "APPROVED",
    "salesState": "APPROVED",
    "productState": "APPROVED",
    "legalState": "APPROVED",
    "owner": "Nimoh Mohankumar",
    "date": "2023-12-06",
    "region": "APAC",
    "businessLine": "Regulatory",
    "products": "Agile reporter",
    "dealTypeStr": "Go n Go",
    "tcvK": 225,
    "ipMaintenanceK": 0,
    "saasK": 0,
    "psVegK": 96,
    "wlVegInvestmentMD": 0,
    "rawDecision": "GO without Committee FINAL",
    "salesStatusStr": "0",
    "comment": "2023"
  },
  {
    "id": "25-2023-035",
    "title": "Dev SOLIAM BO - affichage des SDG pour la consultation)",
    "type": "RFP",
    "status": "SUBMITTED",
    "client": "GENERALI",
    "marginEstimate": 75,
    "workloadMD": 25,
    "financeState": "APPROVED",
    "salesState": "APPROVED",
    "productState": "APPROVED",
    "legalState": "APPROVED",
    "owner": "Mathieu Reynier",
    "date": "2023-06-13",
    "region": "EU",
    "businessLine": "Soliam",
    "products": "Soliam",
    "dealTypeStr": "Go n Go",
    "tcvK": 21,
    "ipMaintenanceK": 0,
    "saasK": 0,
    "psVegK": 21,
    "wlVegInvestmentMD": 0,
    "rawDecision": "GO without Committee FINAL",
    "salesStatusStr": "0",
    "comment": "2023"
  },
  {
    "id": "25-2023-036",
    "title": "DIGITAL APPS_GENERALI _U_0324",
    "type": "RFP",
    "status": "SUBMITTED",
    "client": "GENERALI",
    "marginEstimate": 83,
    "workloadMD": 100,
    "financeState": "APPROVED",
    "salesState": "APPROVED",
    "productState": "APPROVED",
    "legalState": "APPROVED",
    "owner": "Mathieu Reynier",
    "date": "2023-06-13",
    "region": "EU",
    "businessLine": "Digital",
    "products": "Digital",
    "dealTypeStr": "Go n Go",
    "tcvK": 381,
    "ipMaintenanceK": 0,
    "saasK": 0,
    "psVegK": 66,
    "wlVegInvestmentMD": 100,
    "rawDecision": "GO FINAL",
    "salesStatusStr": "0",
    "comment": "2023"
  },
  {
    "id": "26-2023-037",
    "title": "Wafa Assurance Deal 26-2023-037",
    "type": "BID_COMMITTEE_OVERSIGHT",
    "status": "SUBMITTED",
    "client": "Wafa Assurance",
    "marginEstimate": 75,
    "workloadMD": 350,
    "financeState": "APPROVED",
    "salesState": "APPROVED",
    "productState": "APPROVED",
    "legalState": "APPROVED",
    "owner": "Dan Cohen",
    "date": "2023-06-20",
    "region": "EU",
    "businessLine": "Soliam",
    "products": "SOLIAM",
    "dealTypeStr": "Bid n Bid",
    "tcvK": 0,
    "ipMaintenanceK": 0,
    "saasK": 0,
    "psVegK": 0,
    "wlVegInvestmentMD": 0,
    "rawDecision": "BID",
    "salesStatusStr": "BID",
    "comment": "BID"
  },
  {
    "id": "25-2023-038",
    "title": "REGULATORY_BELMONT GREEN_N_1023",
    "type": "RFP",
    "status": "SUBMITTED",
    "client": "Vida Bank",
    "marginEstimate": 76,
    "workloadMD": 336,
    "financeState": "APPROVED",
    "salesState": "APPROVED",
    "productState": "APPROVED",
    "legalState": "APPROVED",
    "owner": "Samuel Welford",
    "date": "2023-06-13",
    "region": "UK",
    "businessLine": "Regulatory",
    "products": "Agile reporter",
    "dealTypeStr": "Go n Go",
    "tcvK": 994,
    "ipMaintenanceK": 0,
    "saasK": 0,
    "psVegK": 234,
    "wlVegInvestmentMD": 0,
    "rawDecision": "GO FINAL",
    "salesStatusStr": "0",
    "comment": "2023"
  },
  {
    "id": "25-2023-039",
    "title": "\\nSOLIFE_NNBE_R_0723\\n",
    "type": "RFP",
    "status": "SUBMITTED",
    "client": "NNBE",
    "marginEstimate": 75,
    "workloadMD": 153,
    "financeState": "APPROVED",
    "salesState": "APPROVED",
    "productState": "APPROVED",
    "legalState": "APPROVED",
    "owner": "Jerome Bastie",
    "date": "2023-06-13",
    "region": "EU",
    "businessLine": "Solife",
    "products": "Solife",
    "dealTypeStr": "Go n Go",
    "tcvK": 107,
    "ipMaintenanceK": 0,
    "saasK": 0,
    "psVegK": 107,
    "wlVegInvestmentMD": 0,
    "rawDecision": "GO without Committee FINAL",
    "salesStatusStr": "0",
    "comment": "2023"
  },
  {
    "id": "25-2023-040",
    "title": "SOLIFE_MAIF_R_0623",
    "type": "RFP",
    "status": "SUBMITTED",
    "client": "MAIF",
    "marginEstimate": 40,
    "workloadMD": 47,
    "financeState": "APPROVED",
    "salesState": "APPROVED",
    "productState": "APPROVED",
    "legalState": "APPROVED",
    "owner": "Dan Cohen",
    "date": "2023-06-13",
    "region": "EU",
    "businessLine": "Solife",
    "products": "Solife",
    "dealTypeStr": "Go n Go",
    "tcvK": 30,
    "ipMaintenanceK": 0,
    "saasK": 0,
    "psVegK": 31,
    "wlVegInvestmentMD": 0,
    "rawDecision": "GO without Committee FINAL",
    "salesStatusStr": "0",
    "comment": "2023"
  },
  {
    "id": "26-2023-041",
    "title": "REGULATORY_COMMONWEALTH BANK OF AUSTRALIA (LONDON)_C_0723",
    "type": "RFP",
    "status": "SUBMITTED",
    "client": "COMMONWEALTH BANK OF AUSTRALIA",
    "marginEstimate": 54,
    "workloadMD": 155,
    "financeState": "APPROVED",
    "salesState": "APPROVED",
    "productState": "APPROVED",
    "legalState": "APPROVED",
    "owner": "Tom Landi",
    "date": "2023-06-20",
    "region": "UK",
    "businessLine": "Regulatory",
    "products": "Agile reporter",
    "dealTypeStr": "Go n Go",
    "tcvK": 525,
    "ipMaintenanceK": 0,
    "saasK": 0,
    "psVegK": 244,
    "wlVegInvestmentMD": 0,
    "rawDecision": "GO without Committee FINAL",
    "salesStatusStr": "0",
    "comment": "2023"
  },
  {
    "id": "26-2023-042",
    "title": "DIGITAL APPS_LIFESTAR_U_0823",
    "type": "RFP",
    "status": "SUBMITTED",
    "client": "LifeStar",
    "marginEstimate": 78,
    "workloadMD": 715,
    "financeState": "APPROVED",
    "salesState": "APPROVED",
    "productState": "APPROVED",
    "legalState": "APPROVED",
    "owner": "Guillaume De Vauxclairs",
    "date": "2023-06-20",
    "region": "EU",
    "businessLine": "Solife",
    "products": "Solife - Digital",
    "dealTypeStr": "Go n Go",
    "tcvK": 2657,
    "ipMaintenanceK": 0,
    "saasK": 0,
    "psVegK": 572,
    "wlVegInvestmentMD": 0,
    "rawDecision": "GO INITIAL",
    "salesStatusStr": "0",
    "comment": "2023"
  },
  {
    "id": "26-2023-043",
    "title": "\\n\\nREGULATORY_BANK OF TOKYO MITSUBISHI UFJ LTD (SINGAPORE)_U_1223\\n",
    "type": "RFP",
    "status": "SUBMITTED",
    "client": "MUFG",
    "marginEstimate": 44,
    "workloadMD": 400,
    "financeState": "APPROVED",
    "salesState": "APPROVED",
    "productState": "APPROVED",
    "legalState": "APPROVED",
    "owner": "Nimoh Mohankumar",
    "date": "2023-06-20",
    "region": "APAC",
    "businessLine": "Regulatory",
    "products": "Agile reporter",
    "dealTypeStr": "Go n Go",
    "tcvK": 980,
    "ipMaintenanceK": 86,
    "saasK": 0,
    "psVegK": 550,
    "wlVegInvestmentMD": 100,
    "rawDecision": "GO FINAL",
    "salesStatusStr": "0",
    "comment": "2023"
  },
  {
    "id": "27-2023-044",
    "title": "\\nMEGARA_MILLENNIUM BCP_C_0324\\n",
    "type": "RFP",
    "status": "SUBMITTED",
    "client": "Millenium BCP",
    "marginEstimate": 100,
    "workloadMD": 350,
    "financeState": "APPROVED",
    "salesState": "APPROVED",
    "productState": "APPROVED",
    "legalState": "APPROVED",
    "owner": "Pablo Garmon",
    "date": "2023-06-27",
    "region": "EU",
    "businessLine": "Megara",
    "products": "Megara",
    "dealTypeStr": "Go n Go",
    "tcvK": 3819,
    "ipMaintenanceK": 0,
    "saasK": 0,
    "psVegK": 0,
    "wlVegInvestmentMD": 0,
    "rawDecision": "GO FINAL",
    "salesStatusStr": "0",
    "comment": "2023"
  },
  {
    "id": "26-2023-045",
    "title": "\\nDIGITAL APPS_GENERALI _U_0323\\nRC PRO",
    "type": "RFP",
    "status": "SUBMITTED",
    "client": "GENERALI",
    "marginEstimate": 88,
    "workloadMD": 1077.5,
    "financeState": "APPROVED",
    "salesState": "APPROVED",
    "productState": "APPROVED",
    "legalState": "APPROVED",
    "owner": "Mathieu Reynier",
    "date": "2023-06-20",
    "region": "EU",
    "businessLine": "Digital",
    "products": "Digital",
    "dealTypeStr": "Go n Go",
    "tcvK": 1955,
    "ipMaintenanceK": 0,
    "saasK": 0,
    "psVegK": 230,
    "wlVegInvestmentMD": 440,
    "rawDecision": "GO FINAL",
    "salesStatusStr": "0",
    "comment": "2023"
  },
  {
    "id": "26-2023-046",
    "title": "\\nSOLIAM_RELYENS_U_1123\\n",
    "type": "RFP",
    "status": "SUBMITTED",
    "client": "Relyens",
    "marginEstimate": 75,
    "workloadMD": 7,
    "financeState": "APPROVED",
    "salesState": "APPROVED",
    "productState": "APPROVED",
    "legalState": "APPROVED",
    "owner": "Jerome Bastie",
    "date": "2023-06-21",
    "region": "EU",
    "businessLine": "Soliam",
    "products": "Soliam",
    "dealTypeStr": "Go n Go",
    "tcvK": 8,
    "ipMaintenanceK": 0,
    "saasK": 0,
    "psVegK": 8,
    "wlVegInvestmentMD": 0,
    "rawDecision": "GO without Committee FINAL",
    "salesStatusStr": "0",
    "comment": "2023"
  },
  {
    "id": "15-2023-047",
    "title": "MEGACOR",
    "type": "BID_COMMITTEE_OVERSIGHT",
    "status": "SUBMITTED",
    "client": "Caceis Germany",
    "marginEstimate": 75,
    "workloadMD": 350,
    "financeState": "APPROVED",
    "salesState": "APPROVED",
    "productState": "APPROVED",
    "legalState": "APPROVED",
    "owner": "Ilyes Mainsi",
    "date": "2023-04-07",
    "region": "EU",
    "businessLine": "Megara",
    "products": "Megara",
    "dealTypeStr": "Bid n Bid",
    "tcvK": 0,
    "ipMaintenanceK": 0,
    "saasK": 0,
    "psVegK": 0,
    "wlVegInvestmentMD": 0,
    "rawDecision": "BID",
    "salesStatusStr": "BID",
    "comment": "BID"
  },
  {
    "id": "27-2023-048",
    "title": "\\nDIGITAL APPS_FEDESA_C_1223\\n",
    "type": "RFP",
    "status": "SUBMITTED",
    "client": "FEDESA",
    "marginEstimate": 100,
    "workloadMD": 350,
    "financeState": "APPROVED",
    "salesState": "APPROVED",
    "productState": "APPROVED",
    "legalState": "APPROVED",
    "owner": "Adrien Gentil",
    "date": "2023-06-27",
    "region": "EU",
    "businessLine": "Digital",
    "products": "Custodix XChanger",
    "dealTypeStr": "Go n Go",
    "tcvK": 255,
    "ipMaintenanceK": 0,
    "saasK": 0,
    "psVegK": 0,
    "wlVegInvestmentMD": 0,
    "rawDecision": "GO FINAL",
    "salesStatusStr": "0",
    "comment": "2023"
  },
  {
    "id": "26-2023-049",
    "title": "\\nDIGITAL APPS_LLOYDS BANK PLC (LONDON)_U_0923\\n",
    "type": "RFP",
    "status": "SUBMITTED",
    "client": "Lloyds Bank",
    "marginEstimate": 95,
    "workloadMD": 230,
    "financeState": "APPROVED",
    "salesState": "APPROVED",
    "productState": "APPROVED",
    "legalState": "APPROVED",
    "owner": "Paul Harris",
    "date": "2023-06-23",
    "region": "UK",
    "businessLine": "Digital",
    "products": "Digital M4life",
    "dealTypeStr": "Go n Go",
    "tcvK": 6115,
    "ipMaintenanceK": 0,
    "saasK": 0,
    "psVegK": 295,
    "wlVegInvestmentMD": 541,
    "rawDecision": "GO FINAL",
    "salesStatusStr": "0",
    "comment": "2023"
  },
  {
    "id": "27-2023-050",
    "title": "Budget extension for MIGRATION",
    "type": "RFP",
    "status": "SUBMITTED",
    "client": "Suravenir",
    "marginEstimate": 58,
    "workloadMD": 120,
    "financeState": "APPROVED",
    "salesState": "APPROVED",
    "productState": "APPROVED",
    "legalState": "APPROVED",
    "owner": "Dan Cohen",
    "date": "2023-06-27",
    "region": "EU",
    "businessLine": "Soliam",
    "products": "Soliam",
    "dealTypeStr": "Go n Go",
    "tcvK": 113,
    "ipMaintenanceK": 0,
    "saasK": 0,
    "psVegK": 47,
    "wlVegInvestmentMD": 0,
    "rawDecision": "GO FINAL",
    "salesStatusStr": "0",
    "comment": "2023"
  },
  {
    "id": "27-2023-051",
    "title": "\\nSOLIFE_CFDP_N_0923\\n",
    "type": "RFP",
    "status": "SUBMITTED",
    "client": "CFDP",
    "marginEstimate": 100,
    "workloadMD": 350,
    "financeState": "APPROVED",
    "salesState": "APPROVED",
    "productState": "APPROVED",
    "legalState": "APPROVED",
    "owner": "Mathieu Reynier",
    "date": "2023-06-27",
    "region": "EU",
    "businessLine": "Solife",
    "products": "Solife - Digital",
    "dealTypeStr": "Go n Go",
    "tcvK": 5080,
    "ipMaintenanceK": 0,
    "saasK": 0,
    "psVegK": 0,
    "wlVegInvestmentMD": 0,
    "rawDecision": "GO FINAL",
    "salesStatusStr": "0",
    "comment": "2023"
  },
  {
    "id": "28-2023-052",
    "title": "\\nGENERALI - SANTE PRO\\n",
    "type": "RFP",
    "status": "REJECTED",
    "client": "GENERALI",
    "marginEstimate": 66,
    "workloadMD": 550,
    "financeState": "APPROVED",
    "salesState": "APPROVED",
    "productState": "APPROVED",
    "legalState": "APPROVED",
    "owner": "Mathieu Reynier",
    "date": "2023-07-04",
    "region": "EU",
    "businessLine": "Digital",
    "products": "Digital",
    "dealTypeStr": "Go n Go",
    "tcvK": 1045,
    "ipMaintenanceK": 0,
    "saasK": 0,
    "psVegK": 358,
    "wlVegInvestmentMD": 123,
    "rawDecision": "GO INITIAL",
    "salesStatusStr": "Canceled",
    "comment": "Ok"
  },
  {
    "id": "28-2023-053",
    "title": "\\nSOLIAM_P&V_N_0623\\nNouvelle Implmentation",
    "type": "RFP",
    "status": "SUBMITTED",
    "client": "P&V and PI",
    "marginEstimate": 83,
    "workloadMD": 147,
    "financeState": "APPROVED",
    "salesState": "APPROVED",
    "productState": "APPROVED",
    "legalState": "APPROVED",
    "owner": "Dan Cohen",
    "date": "2023-07-04",
    "region": "EU",
    "businessLine": "Soliam",
    "products": "Soliam - Custodix",
    "dealTypeStr": "Go n Go",
    "tcvK": 726,
    "ipMaintenanceK": 0,
    "saasK": 0,
    "psVegK": 126,
    "wlVegInvestmentMD": 55,
    "rawDecision": "GO FINAL",
    "salesStatusStr": "0",
    "comment": "2023"
  },
  {
    "id": "28-2023-054",
    "title": "\\nMEGARA_BDF ECMS_C_0823\\n",
    "type": "RFP",
    "status": "SUBMITTED",
    "client": "Banque de France",
    "marginEstimate": 1,
    "workloadMD": 210,
    "financeState": "APPROVED",
    "salesState": "APPROVED",
    "productState": "APPROVED",
    "legalState": "APPROVED",
    "owner": "Ilyes Mainsi",
    "date": "2023-07-04",
    "region": "EU",
    "businessLine": "Megara",
    "products": "Megara",
    "dealTypeStr": "Go n Go",
    "tcvK": 130,
    "ipMaintenanceK": 0,
    "saasK": 0,
    "psVegK": 129,
    "wlVegInvestmentMD": 0,
    "rawDecision": "GO without Committee FINAL",
    "salesStatusStr": "0",
    "comment": "2023"
  },
  {
    "id": "46-2023-055",
    "title": "Partnership (Wells FARGO)",
    "type": "RFP",
    "status": "SUBMITTED",
    "client": "Strategy Innovation Partneship",
    "marginEstimate": 75,
    "workloadMD": 350,
    "financeState": "APPROVED",
    "salesState": "APPROVED",
    "productState": "APPROVED",
    "legalState": "APPROVED",
    "owner": "Alan Blanchard",
    "date": "2023-11-07",
    "region": "UK",
    "businessLine": "Megara",
    "products": "Megara",
    "dealTypeStr": "Go n Go",
    "tcvK": 0,
    "ipMaintenanceK": 0,
    "saasK": 0,
    "psVegK": 0,
    "wlVegInvestmentMD": 0,
    "rawDecision": "GO FINAL",
    "salesStatusStr": "0",
    "comment": "2023"
  },
  {
    "id": "46-2023-056",
    "title": "ERGO Deal 46-2023-056",
    "type": "RFP",
    "status": "SUBMITTED",
    "client": "ERGO",
    "marginEstimate": 100,
    "workloadMD": 350,
    "financeState": "APPROVED",
    "salesState": "APPROVED",
    "productState": "APPROVED",
    "legalState": "APPROVED",
    "owner": "Guillaume De Vauxclairs",
    "date": "2023-11-07",
    "region": "EU",
    "businessLine": "Solife",
    "products": "Solife - Digital",
    "dealTypeStr": "Go n Go",
    "tcvK": 10369,
    "ipMaintenanceK": 0,
    "saasK": 0,
    "psVegK": 0,
    "wlVegInvestmentMD": 0,
    "rawDecision": "GO FINAL",
    "salesStatusStr": "0",
    "comment": "2023"
  },
  {
    "id": "28-2023-057",
    "title": "\\nSOLIFE_NNS_U_0723\\n",
    "type": "RFP",
    "status": "SUBMITTED",
    "client": "NNS",
    "marginEstimate": 67,
    "workloadMD": 312,
    "financeState": "APPROVED",
    "salesState": "APPROVED",
    "productState": "APPROVED",
    "legalState": "APPROVED",
    "owner": "Guillaume De Vauxclairs",
    "date": "2023-07-04",
    "region": "EU",
    "businessLine": "Solife",
    "products": "Solife",
    "dealTypeStr": "Go n Go",
    "tcvK": 724,
    "ipMaintenanceK": 0,
    "saasK": 0,
    "psVegK": 241,
    "wlVegInvestmentMD": 0,
    "rawDecision": "GO FINAL",
    "salesStatusStr": "0",
    "comment": "2023"
  },
  {
    "id": "29-2023-058",
    "title": "\\nCOLLINE_MILLENNIUM BCP_R_0923\\n",
    "type": "RFP",
    "status": "SUBMITTED",
    "client": "Millenium BCP",
    "marginEstimate": 61,
    "workloadMD": 312,
    "financeState": "APPROVED",
    "salesState": "APPROVED",
    "productState": "APPROVED",
    "legalState": "APPROVED",
    "owner": "Pablo Garmon",
    "date": "2023-07-11",
    "region": "EU",
    "businessLine": "Colline",
    "products": "Colline",
    "dealTypeStr": "Go n Go",
    "tcvK": 625,
    "ipMaintenanceK": 0,
    "saasK": 0,
    "psVegK": 241,
    "wlVegInvestmentMD": 0,
    "rawDecision": "GO FINAL",
    "salesStatusStr": "0",
    "comment": "2023"
  },
  {
    "id": "24-2023-059",
    "title": "\\nCOLLINE_WELLS FARGO SECURITIES (CHARLOTTE - COLLINE)_U_0623\\n",
    "type": "RFP",
    "status": "SUBMITTED",
    "client": "Wells Fargo",
    "marginEstimate": 100,
    "workloadMD": 350,
    "financeState": "APPROVED",
    "salesState": "APPROVED",
    "productState": "APPROVED",
    "legalState": "APPROVED",
    "owner": "Terrance Baum",
    "date": "2023-06-06",
    "region": "Americas",
    "businessLine": "Colline",
    "products": "Colline",
    "dealTypeStr": "Go n Go",
    "tcvK": 4300,
    "ipMaintenanceK": 0,
    "saasK": 0,
    "psVegK": 0,
    "wlVegInvestmentMD": 0,
    "rawDecision": "GO FINAL",
    "salesStatusStr": "0",
    "comment": "2023"
  },
  {
    "id": "30-2023-060",
    "title": "\\nCOLLINE_NORTHERN TRUST_R_1223\\n",
    "type": "RFP",
    "status": "SUBMITTED",
    "client": "Northern Trust",
    "marginEstimate": 100,
    "workloadMD": 350,
    "financeState": "APPROVED",
    "salesState": "APPROVED",
    "productState": "APPROVED",
    "legalState": "APPROVED",
    "owner": "Terrance Baum",
    "date": "2023-07-18",
    "region": "Americas",
    "businessLine": "Colline",
    "products": "Colline",
    "dealTypeStr": "Go n Go",
    "tcvK": 4543,
    "ipMaintenanceK": 0,
    "saasK": 0,
    "psVegK": 0,
    "wlVegInvestmentMD": 0,
    "rawDecision": "GO FINAL",
    "salesStatusStr": "0",
    "comment": "2023"
  },
  {
    "id": "27-2023-061",
    "title": "\\nOBERON_MIZUHO BANK LTD (SINGAPORE)_R_0723\\n",
    "type": "RFP",
    "status": "CONTRACT_SIGNATURE",
    "client": "Mizuho",
    "marginEstimate": 100,
    "workloadMD": 350,
    "financeState": "APPROVED",
    "salesState": "APPROVED",
    "productState": "APPROVED",
    "legalState": "APPROVED",
    "owner": "Danny Lim",
    "date": "2023-07-01",
    "region": "APAC",
    "businessLine": "Oberon",
    "products": "Oberon",
    "dealTypeStr": "Go n Go",
    "tcvK": 99,
    "ipMaintenanceK": 0,
    "saasK": 0,
    "psVegK": 0,
    "wlVegInvestmentMD": 0,
    "rawDecision": "GO FINAL",
    "salesStatusStr": "Won",
    "comment": "2023"
  },
  {
    "id": "27-2023-062",
    "title": "\\nMizuho SG FirmRisk VaR Extension\\n\\n",
    "type": "RFP",
    "status": "CONTRACT_SIGNATURE",
    "client": "Mizuho",
    "marginEstimate": 100,
    "workloadMD": 350,
    "financeState": "APPROVED",
    "salesState": "APPROVED",
    "productState": "APPROVED",
    "legalState": "APPROVED",
    "owner": "Danny Lim",
    "date": "2023-07-01",
    "region": "APAC",
    "businessLine": "Oberon",
    "products": "Oberon",
    "dealTypeStr": "Go n Go",
    "tcvK": 88,
    "ipMaintenanceK": 0,
    "saasK": 0,
    "psVegK": 0,
    "wlVegInvestmentMD": 0,
    "rawDecision": "GO FINAL",
    "salesStatusStr": "Won",
    "comment": "2023"
  },
  {
    "id": "28-2023-063",
    "title": "AG_INSURANCE_SOLIFE_SERVICE_Q3_2023\\n",
    "type": "RFP",
    "status": "SUBMITTED",
    "client": "AG Insurance",
    "marginEstimate": 75,
    "workloadMD": 350,
    "financeState": "APPROVED",
    "salesState": "APPROVED",
    "productState": "APPROVED",
    "legalState": "APPROVED",
    "owner": "Jerome Bastie",
    "date": "2023-07-07",
    "region": "EU",
    "businessLine": "Solife",
    "products": "Solife",
    "dealTypeStr": "Go n Go",
    "tcvK": 247,
    "ipMaintenanceK": 0,
    "saasK": 0,
    "psVegK": 247,
    "wlVegInvestmentMD": 0,
    "rawDecision": "GO without Committee FINAL",
    "salesStatusStr": "0",
    "comment": "2023"
  },
  {
    "id": "46-2023-064",
    "title": "\\nCOLLINE_LOMBARD ODIER (GENEVA)_R_0624\\n",
    "type": "RFP",
    "status": "SUBMITTED",
    "client": "Lombard Odier",
    "marginEstimate": 100,
    "workloadMD": 350,
    "financeState": "APPROVED",
    "salesState": "APPROVED",
    "productState": "APPROVED",
    "legalState": "APPROVED",
    "owner": "Raphael Suria",
    "date": "2023-11-07",
    "region": "EU",
    "businessLine": "Colline",
    "products": "Colline",
    "dealTypeStr": "Go n Go",
    "tcvK": 638,
    "ipMaintenanceK": 0,
    "saasK": 0,
    "psVegK": 0,
    "wlVegInvestmentMD": 0,
    "rawDecision": "GO FINAL",
    "salesStatusStr": "0",
    "comment": "2023"
  },
  {
    "id": "30-2023-065",
    "title": "\\nSOLIFE_CARDIF LUX VIE_C_0923\\nCardif Lux Vie_Solife_Maintenance engagement 5 ans + Extended +",
    "type": "RFP",
    "status": "SUBMITTED",
    "client": "Cardif Lux Vie",
    "marginEstimate": 85,
    "workloadMD": 1195,
    "financeState": "APPROVED",
    "salesState": "APPROVED",
    "productState": "APPROVED",
    "legalState": "APPROVED",
    "owner": "Anne Thiel",
    "date": "2023-07-18",
    "region": "EU",
    "businessLine": "Solife",
    "products": "Solife - Digital",
    "dealTypeStr": "Go n Go",
    "tcvK": 6570,
    "ipMaintenanceK": 0,
    "saasK": 0,
    "psVegK": 1000,
    "wlVegInvestmentMD": 0,
    "rawDecision": "GO FINAL",
    "salesStatusStr": "0",
    "comment": "2023"
  },
  {
    "id": "30-2023-066",
    "title": "OnBoarding BlackRock Custody Activity?",
    "type": "RFP",
    "status": "SUBMITTED",
    "client": "S3 Mexico",
    "marginEstimate": 39,
    "workloadMD": 644,
    "financeState": "APPROVED",
    "salesState": "APPROVED",
    "productState": "APPROVED",
    "legalState": "APPROVED",
    "owner": "Haykel Manai",
    "date": "2023-07-20",
    "region": "Americas",
    "businessLine": "Megara",
    "products": "Megara - Digital",
    "dealTypeStr": "Go n Go",
    "tcvK": 723,
    "ipMaintenanceK": 0,
    "saasK": 0,
    "psVegK": 442,
    "wlVegInvestmentMD": 163,
    "rawDecision": "GO FINAL",
    "salesStatusStr": "0",
    "comment": "2023"
  },
  {
    "id": "31-2023-067",
    "title": "building connectors",
    "type": "BID_COMMITTEE_OVERSIGHT",
    "status": "SUBMITTED",
    "client": "Thought Machines TM",
    "marginEstimate": 75,
    "workloadMD": 350,
    "financeState": "APPROVED",
    "salesState": "APPROVED",
    "productState": "APPROVED",
    "legalState": "APPROVED",
    "owner": "Malcolm Arnold",
    "date": "2023-07-26",
    "region": "UK",
    "businessLine": "Regulatory",
    "products": "Agile Reporter",
    "dealTypeStr": "Bid n Bid",
    "tcvK": 0,
    "ipMaintenanceK": 0,
    "saasK": 0,
    "psVegK": 0,
    "wlVegInvestmentMD": 0,
    "rawDecision": "BID",
    "salesStatusStr": "BID",
    "comment": "BID"
  },
  {
    "id": "31-2023-068",
    "title": "\\nCOLLINE_NORTHERN TRUST_R_1223\\n",
    "type": "RFP",
    "status": "SUBMITTED",
    "client": "Northern Trust",
    "marginEstimate": 98,
    "workloadMD": 40,
    "financeState": "APPROVED",
    "salesState": "APPROVED",
    "productState": "APPROVED",
    "legalState": "APPROVED",
    "owner": "Terrance Baum",
    "date": "2023-07-26",
    "region": "Americas",
    "businessLine": "Colline",
    "products": "Colline",
    "dealTypeStr": "Go n Go",
    "tcvK": 4543,
    "ipMaintenanceK": 0,
    "saasK": 0,
    "psVegK": 91,
    "wlVegInvestmentMD": 0,
    "rawDecision": "GO FINAL",
    "salesStatusStr": "0",
    "comment": "2023"
  },
  {
    "id": "31-2023-069",
    "title": "SOLIAM_ROTHSCHILD & CO_U_1223\\n",
    "type": "RFP",
    "status": "SUBMITTED",
    "client": "Rothschild & Co",
    "marginEstimate": 100,
    "workloadMD": 350,
    "financeState": "APPROVED",
    "salesState": "APPROVED",
    "productState": "APPROVED",
    "legalState": "APPROVED",
    "owner": "Sylvain Chene",
    "date": "2023-07-26",
    "region": "EU",
    "businessLine": "Soliam",
    "products": "SOLIAM",
    "dealTypeStr": "Go n Go",
    "tcvK": 394,
    "ipMaintenanceK": 0,
    "saasK": 0,
    "psVegK": 0,
    "wlVegInvestmentMD": 0,
    "rawDecision": "GO FINAL",
    "salesStatusStr": "0",
    "comment": "2023"
  },
  {
    "id": "02-2023-070",
    "title": "Temenos Partnership Deal 02-2023-070",
    "type": "BID_COMMITTEE_OVERSIGHT",
    "status": "SUBMITTED",
    "client": "Temenos Partnership",
    "marginEstimate": 75,
    "workloadMD": 350,
    "financeState": "APPROVED",
    "salesState": "APPROVED",
    "productState": "APPROVED",
    "legalState": "APPROVED",
    "owner": "Nimoh Mohankumar",
    "date": "2023-01-08",
    "region": "APAC",
    "businessLine": "Regulatory",
    "products": "Agile reporter",
    "dealTypeStr": "Bid n Bid",
    "tcvK": 0,
    "ipMaintenanceK": 0,
    "saasK": 0,
    "psVegK": 0,
    "wlVegInvestmentMD": 0,
    "rawDecision": "BID",
    "salesStatusStr": "BID",
    "comment": "BID"
  },
  {
    "id": "31-2023-071",
    "title": "\\nSOLIAM_ALLIANZ BELGIUM_U_0324\\nAllianz BE - SOLIAM - Saas offer",
    "type": "RFP",
    "status": "SUBMITTED",
    "client": "Allianz BE",
    "marginEstimate": 100,
    "workloadMD": 350,
    "financeState": "APPROVED",
    "salesState": "APPROVED",
    "productState": "APPROVED",
    "legalState": "APPROVED",
    "owner": "Dan Cohen",
    "date": "2023-07-26",
    "region": "EU",
    "businessLine": "Soliam",
    "products": "SOLIAM",
    "dealTypeStr": "Go n Go",
    "tcvK": 1297,
    "ipMaintenanceK": 0,
    "saasK": 0,
    "psVegK": 0,
    "wlVegInvestmentMD": 0,
    "rawDecision": "GO FINAL",
    "salesStatusStr": "0",
    "comment": "2023"
  },
  {
    "id": "32-2023-072",
    "title": "\\nMEGARA_SGSS_R_1223\\n",
    "type": "RFP",
    "status": "SUBMITTED",
    "client": "SGSS Madrid",
    "marginEstimate": 100,
    "workloadMD": 350,
    "financeState": "APPROVED",
    "salesState": "APPROVED",
    "productState": "APPROVED",
    "legalState": "APPROVED",
    "owner": "Pablo Garmon",
    "date": "2023-08-01",
    "region": "EU",
    "businessLine": "Megara",
    "products": "Megara",
    "dealTypeStr": "Go n Go",
    "tcvK": 2150,
    "ipMaintenanceK": 0,
    "saasK": 0,
    "psVegK": 0,
    "wlVegInvestmentMD": 0,
    "rawDecision": "GO FINAL",
    "salesStatusStr": "https://vermeg.sharepoint.com/sites/COMPLIANCE2/VERMEG%20ENGAGEMENT%20COMMITTEE%20VEG/Forms/AllItems.aspx?newTargetListUrl=%2Fsites%2FCOMPLIANCE2%2FVERMEG%20ENGAGEMENT%20COMMITTEE%20VEG&viewpath=%2Fsites%2FCOMPLIANCE2%2FVERMEG%20ENGAGEMENT%20COMMITTEE%20VEG%2FForms%2FAllItems%2Easpx&id=%2Fsites%2FCOMPLIANCE2%2FVERMEG%20ENGAGEMENT%20COMMITTEE%20VEG%2FVEG280723%2FLBG%20GO%20n%20GO&viewid=31554ee6%2Df523%2D484a%2Db2e1%2D71a45728ac93",
    "comment": "#N/A"
  },
  {
    "id": "02-2023-076",
    "title": "\\nREGULATORY_DF CAPITAL_N_0624\\n",
    "type": "RFP",
    "status": "SUBMITTED",
    "client": "DF CAPITAL",
    "marginEstimate": 51,
    "workloadMD": 213,
    "financeState": "APPROVED",
    "salesState": "APPROVED",
    "productState": "APPROVED",
    "legalState": "APPROVED",
    "owner": "Samuel Welford",
    "date": "2023-01-08",
    "region": "UK",
    "businessLine": "Regulatory",
    "products": "Agile Reporter",
    "dealTypeStr": "Go n Go",
    "tcvK": 714,
    "ipMaintenanceK": 0,
    "saasK": 0,
    "psVegK": 351,
    "wlVegInvestmentMD": 0,
    "rawDecision": "GO FINAL",
    "salesStatusStr": "Open",
    "comment": "60,000K"
  },
  {
    "id": "33-2023-079",
    "title": "\\nFiera - COLLINE - 3 year term renewal\\n\\n",
    "type": "RFP",
    "status": "CONTRACT_SIGNATURE",
    "client": "FIERA",
    "marginEstimate": 100,
    "workloadMD": 350,
    "financeState": "APPROVED",
    "salesState": "APPROVED",
    "productState": "APPROVED",
    "legalState": "APPROVED",
    "owner": "Terrance Baum",
    "date": "2023-08-08",
    "region": "Americas",
    "businessLine": "Colline",
    "products": "Colline",
    "dealTypeStr": "Go n Go",
    "tcvK": 291.3,
    "ipMaintenanceK": 0,
    "saasK": 0,
    "psVegK": 0,
    "wlVegInvestmentMD": 0,
    "rawDecision": "GO FINAL",
    "salesStatusStr": "Won",
    "comment": "2023"
  },
  {
    "id": "33-2023-080",
    "title": "new deal",
    "type": "BID_COMMITTEE_OVERSIGHT",
    "status": "SUBMITTED",
    "client": "AXA BANQUE",
    "marginEstimate": 75,
    "workloadMD": 350,
    "financeState": "APPROVED",
    "salesState": "APPROVED",
    "productState": "APPROVED",
    "legalState": "APPROVED",
    "owner": "Eric Bemelmans",
    "date": "2023-08-08",
    "region": "EU",
    "businessLine": "Digital",
    "products": "Digital",
    "dealTypeStr": "Bid n Bid",
    "tcvK": 0,
    "ipMaintenanceK": 0,
    "saasK": 0,
    "psVegK": 0,
    "wlVegInvestmentMD": 0,
    "rawDecision": "BID",
    "salesStatusStr": "BID",
    "comment": "BID"
  },
  {
    "id": "19-2026-1947",
    "title": "Capitolis Additional PS",
    "type": "RFP",
    "status": "APPROVED",
    "client": "Capitolis",
    "marginEstimate": 75,
    "workloadMD": 10,
    "financeState": "APPROVED",
    "salesState": "APPROVED",
    "productState": "APPROVED",
    "legalState": "APPROVED",
    "owner": "Nimoh Mohankumar",
    "date": "2026-04-28",
    "region": "Americas",
    "businessLine": "Colline",
    "products": "Coline",
    "dealTypeStr": "Go n Go",
    "tcvK": 16,
    "ipMaintenanceK": 0,
    "saasK": 0,
    "psVegK": 16,
    "wlVegInvestmentMD": 0,
    "rawDecision": "GO FINAL",
    "salesStatusStr": "Won Candidate",
    "comment": "OK"
  },
  {
    "id": "19-2026-1956",
    "title": "BdF Embassy RPS",
    "type": "RFP",
    "status": "SUBMITTED",
    "client": "Banque de France",
    "marginEstimate": 81,
    "workloadMD": 283,
    "financeState": "APPROVED",
    "salesState": "APPROVED",
    "productState": "APPROVED",
    "legalState": "APPROVED",
    "owner": "Ilyes Mainsi",
    "date": "2026-05-05",
    "region": "EU",
    "businessLine": "Megara",
    "products": "Megara",
    "dealTypeStr": "Go n Go",
    "tcvK": 725,
    "ipMaintenanceK": 50,
    "saasK": 0,
    "psVegK": 135,
    "wlVegInvestmentMD": 34,
    "rawDecision": "GO FINAL",
    "salesStatusStr": "Open",
    "comment": "OK"
  },
  {
    "id": "49-2025-1691",
    "title": "GENERALI - RENEW 6 MOIS - NFSM + BES",
    "type": "RFP",
    "status": "CONTRACT_SIGNATURE",
    "client": "GENERALI",
    "marginEstimate": 100,
    "workloadMD": 350,
    "financeState": "APPROVED",
    "salesState": "APPROVED",
    "productState": "APPROVED",
    "legalState": "APPROVED",
    "owner": "Mathieu Reynier",
    "date": "2025-12-24",
    "region": "EU",
    "businessLine": "Digital",
    "products": "Digital",
    "dealTypeStr": "Go n Go",
    "tcvK": 445,
    "ipMaintenanceK": 163,
    "saasK": 281,
    "psVegK": 0,
    "wlVegInvestmentMD": 0,
    "rawDecision": "GO FINAL",
    "salesStatusStr": "Won",
    "comment": "OK"
  }
];
